spring:
  jpa:
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: SHOWCASE-1
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8081
topic:
  update-process: UPDATE-PROCESS